
# Server
server.port=8081

# Database
spring.datasource.url=jdbc:mariadb://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Email (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server pepper
app.pepper=${APP_PEPPER}

# Keycloak
keycloak.server-url=${KEYCLOK_SERVER}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.client-id-app=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER}
keycloak.introspectUrl=${KEYCLOAK_INTROSPECT}

# CORS
spring.web.cors.allowed-origins=${SPRING_WEB_CORS_ALLOWED_ORIGINS}