spring.application.name=appTim
server.port=8081

# Database
spring.datasource.url=jdbc:mariadb://localhost:3306/tim
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Email (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lehbac05@gmail.com
spring.mail.password=cvxf lhyv voug wmla
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server pepper cho HMAC
app.pepper=X7k9pL2mQ8vJ5yH3wR1tU4oP6sZ0xN2cE8fD4bG6iA3jM9qW

# File upload directory
upload.folder=D:/BE-Project/ALM-Team-Tim-BE/uploads

# Keycloak
keycloak.server-url=https://id.dev.codegym.vn/auth
keycloak.realm=codegym-software-nhom-4
keycloak.client-id-app=tim_app
keycloak.client-secret=adaa997e-f43b-4dad-abcb-454949d18162

#Size file
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Tomcat limits
server.tomcat.max-http-form-post-size=100MB
# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
# Static file serving
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.web.resources.cache.cachecontrol.max-age=3600



