ALTER TABLE notifications 
MODIFY COLUMN notification_type ENUM(
    'POST_REACTION','POST_COMMENT','COMMENT_REACTION','COMMENT_REPLY',
    'REPLY_REACTION','USER_FOLLOW','POST_MENTION','COMMENT_MENTION',
    'SYSTEM_ANNOUNCEMENT','LATE_ATTENDANCE_OPENED',
    'ATTENDANCE_REMINDER_LATE','ATTENDANCE_REMINDER_ENDING'
) NOT NULL;