SET FOREIGN_KEY_CHECKS=0;
create table attendance_records (marked_by integer not null, student_id integer not null, id bigint not null auto_increment, marked_at datetime(6), schedule_id bigint not null, notes varchar(255), status enum ('absent','excused','late','present'), primary key (id)) engine=InnoDB;
create table attendance_sessions (is_late bit, late_threshold_minutes integer, opened_by integer not null, closed_at datetime(6), id bigint not null auto_increment, opened_at datetime(6), schedule_id bigint not null, primary key (id)) engine=InnoDB;
create table behavior_point_types (behavior_id integer not null, id integer not null auto_increment, point_type_id integer not null, points integer not null, created_at datetime(6) not null, notification_template_id bigint, primary key (id)) engine=InnoDB;
create table class_members (id bigint not null auto_increment, lop_id bigint not null, ngay_tham_gia datetime(6), nguoi_dung_id bigint not null, vai_tro enum ('giao_vien','sinh_vien'), primary key (id)) engine=InnoDB;
create table class_module (module_id integer not null, class_id bigint not null, created_at datetime(6), id bigint not null auto_increment, schedule_type enum ('fixed','flexible','offline','online'), primary key (id)) engine=InnoDB;
create table class_module_schedule_teacher (assigned_at datetime(6), class_module_schedule_id bigint not null, id bigint not null auto_increment, user_id bigint not null, role enum ('TEACHER'), primary key (id)) engine=InnoDB;
create table class_module_schedules (module_id integer, class_id bigint, class_module_id bigint, end_date datetime(6), id bigint not null auto_increment, instructor_id bigint, module_session_id bigint, start_date datetime(6), status enum ('completed','ongoing','planned'), primary key (id)) engine=InnoDB;
create table class_module_teacher (assigned_at datetime(6), class_module_id bigint not null, id bigint not null auto_increment, user_id bigint not null, role enum ('TEACHER'), primary key (id)) engine=InnoDB;
create table classes (jobs_enabled bit not null, program_id integer, id bigint not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table comments (bai_viet_id bigint not null, files_id bigint, id bigint not null auto_increment, nguoi_dung_id bigint not null, reaction_id bigint, thoi_gian_cap_nhat datetime(6), thoi_gian_tao datetime(6), noi_dung varchar(255), emotion enum ('angry','haha','like','love','sad'), primary key (id)) engine=InnoDB;
create table companies (founding_date date, created_at datetime(6), id bigint not null auto_increment, address TEXT, benefits TEXT, introduction TEXT, logo_url varchar(255), name varchar(255) not null, phone varchar(255), profile_url varchar(255), short_name varchar(255), size varchar(255), status varchar(255), website varchar(255), type enum ('CODEGYM_TO_PARTNER','FORMER_PARTNER','OFFICIAL_PARTNER','PARTNER_TO_CODEGYM','POTENTIAL_PARTNER'), primary key (id)) engine=InnoDB;
create table company_markets (company_id bigint not null, market_name varchar(255)) engine=InnoDB;
create table company_products (company_id bigint not null, product_name varchar(255)) engine=InnoDB;
create table company_regions (company_id bigint not null, region_name varchar(255)) engine=InnoDB;
create table company_technologies (company_id bigint not null, tech_name varchar(255)) engine=InnoDB;
create table contact_persons (dob date, company_id bigint, id bigint not null auto_increment, email varchar(255), name varchar(255), phone varchar(255), position varchar(255), primary key (id)) engine=InnoDB;
create table coupons (active bit not null, discount_value decimal(38,2) not null, end_date date not null, quantity integer, start_date date not null, used_count integer, id bigint not null auto_increment, center_scope varchar(255), code varchar(255) not null, discount_type enum ('AMOUNT','PERCENT'), scenario enum ('DEDUCT_FIRST_FULL','DEDUCT_LAST_FULL','PARTIAL_FIRST_THEN_SPREAD','SPREAD_EVENLY'), primary key (id)) engine=InnoDB;
create table files (id integer not null auto_increment, comment_id bigint, file_size bigint, post_id bigint, reply_comment_id bigint, file_name varchar(255), file_url varchar(255) not null, file_type enum ('DOCUMENT','IMAGE','VIDEO') not null, primary key (id)) engine=InnoDB;
create table form_templates (is_active bit, id bigint not null auto_increment, code varchar(255) not null, description TEXT, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table gamification_achievement_levels (achievement_id integer not null, id integer not null auto_increment, min_points_required integer, required_point_type_id integer, created_at datetime(6) not null, notification_template_id bigint, level_name varchar(100) not null, image_url_levels varchar(255), required_point_type_enum enum ('COMPETENCE','DILIGENCE','EXPERIENCE'), primary key (id)) engine=InnoDB;
create table gamification_achievements (created_by integer, id integer not null auto_increment, created_at datetime(6) not null, name varchar(100) not null, image_url varchar(255), primary key (id)) engine=InnoDB;
create table gamification_behavior_groups (id integer not null auto_increment, created_at datetime(6) not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table gamification_behaviors (group_id integer not null, id integer not null auto_increment, max_times_per_frequency integer, point_competence integer, point_diligence integer, point_experience integer, created_at datetime(6) not null, notification_template_competence_id bigint, notification_template_diligence_id bigint, notification_template_experience_id bigint, name varchar(255) not null, frequency_type enum ('DAILY','MONTHLY','ONCE','UNLIMITED','WEEKLY') not null, primary key (id)) engine=InnoDB;
create table gamification_point_types (created_by integer, id integer not null auto_increment, is_active bit not null, max_points integer, show_on_dashboard bit not null, created_at datetime(6) not null, name varchar(50) not null, description TEXT, image_url varchar(255), primary key (id)) engine=InnoDB;
create table grade_history (new_score decimal(38,2), old_score decimal(38,2), changed_at datetime(6), changed_by_user_id bigint not null, grade_id bigint not null, id bigint not null auto_increment, component_changed varchar(255) not null, primary key (id)) engine=InnoDB;
create table grades (entry_date date, practice_score decimal(38,2), theory_score decimal(38,2), class_module_id bigint not null, created_at datetime(6), entered_by_user_id bigint, id bigint not null auto_increment, student_id bigint not null, updated_at datetime(6), status enum ('ACTIVE','DELETED') not null, primary key (id)) engine=InnoDB;
create table invalidated_tokens (expiry_date datetime(6) not null, jti varchar(255) not null, primary key (jti)) engine=InnoDB;
create table job_activities (happened_at date, created_at datetime(6), id bigint not null auto_increment, job_lead_id bigint, content TEXT, file_url varchar(255), note TEXT, salary_amount varchar(255), activity_type enum ('INTERVIEW','INTERVIEW_SCHEDULED','OFFER_RECEIVED','OFFICIAL_CONTRACT','PROBATION_CONTRACT','SEND_CV'), primary key (id)) engine=InnoDB;
create table job_applications (applied_at datetime(6), class_id bigint, company_id bigint, id bigint not null auto_increment, student_id bigint, cv_url varchar(255), note varchar(255), status enum ('CANCELLED','FAILED','INTERVIEW','INTERVIEW_SCHEDULED','OFFER_RECEIVED','OFFICIAL_CONTRACT','PROBATION_CONTRACT','SENT_CV'), primary key (id)) engine=InnoDB;
create table job_leads (created_by_admin bit not null, created_at datetime(6), id bigint not null auto_increment, student_id bigint, address varchar(255), company_name varchar(255) not null, short_name varchar(255), website varchar(255), status enum ('APPLIED','FAILED','IGNORED','INTERVIEWING','NEW','OFFER','OFFICIAL','PROBATION'), primary key (id)) engine=InnoDB;
create table module_sessions (module_id integer, session_number integer not null, id bigint not null auto_increment, content TEXT, title varchar(255), primary key (id)) engine=InnoDB;
create table modules (id integer not null auto_increment, description TEXT, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table notification_templates (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), title varchar(500) not null, content TEXT not null, icon_url varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table notifications (is_read bit not null, created_at datetime(6) not null, id bigint not null auto_increment, read_at datetime(6), receiver_id bigint not null, sender_id bigint, target_id bigint, target_type varchar(50), icon_url varchar(500), content TEXT, title varchar(255) not null, notification_type enum ('ATTENDANCE_REMINDER_ENDING','ATTENDANCE_REMINDER_LATE','BLOG_NEW','COMMENT_MENTION','COMMENT_REACTION','COMMENT_REPLY','GAMIFICATION_ACHIEVEMENT_UNLOCKED','GAMIFICATION_LEVEL_UP','GAMIFICATION_POINT_EARNED','GAMIFICATION_RANKING_CHANGE','GRADE_NEW','GRADE_UPDATED','INTERNSHIP_LOG_UPDATE','INTERNSHIP_STATUS_UPDATE','LATE_ATTENDANCE_OPENED','POST_COMMENT','POST_MENTION','POST_REACTION','REPLY_REACTION','SYSTEM_ANNOUNCEMENT','TUITION_OVERDUE','TUITION_REMINDER','USER_FOLLOW') not null, primary key (id)) engine=InnoDB;
create table password_reset_requests (attempts integer, used bit, created_at datetime(6), expires_at datetime(6) not null, id bigint not null auto_increment, user_id bigint not null, request_ip varchar(45), otp_hash varchar(255), user_agent varchar(255), token_type enum ('LINK','OTP'), primary key (id)) engine=InnoDB;
create table permissions (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table posts (tong_comments integer, tong_reactions integer, id bigint not null auto_increment, nguoi_dung_id bigint not null, thoi_gian_cap_nhat datetime(6), thoi_gian_tao datetime(6), link_domain varchar(200), link_image_url varchar(500), link_title varchar(500), link_url varchar(500), link_description varchar(1000), noi_dung varchar(255), quyen_rieng_tu enum ('friends','only_me','open'), primary key (id)) engine=InnoDB;
create table program_modules (module_id integer not null, position integer, program_id integer not null, primary key (module_id, program_id)) engine=InnoDB;
create table programs (id integer not null auto_increment, description TEXT, name varchar(255), primary key (id)) engine=InnoDB;
create table ranking (total_competence_score integer, total_diligence_score integer, total_experience_score integer, classes_id bigint, courses_id bigint, id bigint not null auto_increment, nguoi_dung_id bigint not null, update_time datetime(6), primary key (id)) engine=InnoDB;
create table ranking_monthly (rank_position integer, total_competence_score integer, total_diligence_score integer, total_experience_score integer, month_year varchar(7) not null, class_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), user_id bigint not null, primary key (id)) engine=InnoDB;
create table reactions (bai_viet_id bigint, comment_id bigint, id bigint not null auto_increment, nguoi_dung_id bigint not null, reply_comment_id bigint, thoi_gian_tao datetime(6), loai_cam_xuc enum ('angry','haha','like','love','sad','wow'), primary key (id)) engine=InnoDB;
create table reply_comments (comments_id bigint not null, files_id bigint, id bigint not null auto_increment, nguoi_dung_id bigint not null, thoi_gian_cap_nhat datetime(6), thoi_gian_tao datetime(6), noi_dung varchar(255), emotion enum ('angry','haha','like','love','sad'), primary key (id)) engine=InnoDB;
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table student_forms (end_date date, fee_amount decimal(38,2), start_date date, academic_user_id bigint, accountant_user_id bigint, admin_user_id bigint, class_id bigint not null, coach_user_id bigint, created_at datetime(6), created_by_user_id bigint not null, id bigint not null auto_increment, module_id bigint, module_session_id bigint, student_id bigint not null, template_id bigint not null, updated_at datetime(6), academic_note varchar(255), accountant_note varchar(255), admin_note varchar(255), coach_note varchar(255), email varchar(255), reason varchar(255), so_dien_thoai varchar(255), academic_approval enum ('APPROVED','PENDING','PROCESSING','REJECTED'), accountant_approval enum ('APPROVED','PENDING','PROCESSING','REJECTED'), admin_approval enum ('APPROVED','PENDING','PROCESSING','REJECTED'), coach_approval enum ('APPROVED','PENDING','PROCESSING','REJECTED'), status enum ('APPROVED','PENDING','PROCESSING','REJECTED'), primary key (id)) engine=InnoDB;
create table student_payment_schedule_history (new_due_date date not null, old_due_date date, created_at datetime(6) not null, id bigint not null auto_increment, modified_by_user_id bigint, schedule_id bigint not null, reason varchar(255), primary key (id)) engine=InnoDB;
create table student_payment_schedules (due_date date, expected_amount decimal(38,2), from_date date, installment_number integer, paid_amount decimal(38,2), id bigint not null auto_increment, student_tuition_id bigint not null, status enum ('CANCELLED','OVERDUE','PAID','PARTIAL','PENDING'), primary key (id)) engine=InnoDB;
create table student_tuitions (enrollment_date date, total_actual_fee decimal(38,2), id bigint not null auto_increment, student_id bigint not null, tuition_route_id bigint not null, status enum ('ACTIVE','COMPLETED','DROPPED','PENDING','RESERVED'), primary key (id)) engine=InnoDB;
create table tuition_installment_configs (base_amount decimal(15,2) not null, days_from_previous integer not null, installment_number integer not null, id bigint not null auto_increment, tuition_route_id bigint not null, primary key (id)) engine=InnoDB;
create table tuition_receipts (amount decimal(38,2), collector_id bigint, id bigint not null auto_increment, payment_date datetime(6), payment_schedule_id bigint, transaction_id bigint, note varchar(255), payment_method varchar(255), receipt_code varchar(255) not null, primary key (id)) engine=InnoDB;
create table tuition_routes (admission_fee decimal(38,2), first_month_fee decimal(38,2), frequency integer, number_of_installments integer, program_id integer not null, total_listed_fee decimal(38,2), id bigint not null auto_increment, description TEXT, name varchar(255) not null, type enum ('FULL_TIME','PART_TIME') not null, primary key (id)) engine=InnoDB;
create table tuition_transactions (amount decimal(38,2) not null, id bigint not null auto_increment, performed_by bigint, student_tuition_id bigint not null, transaction_date datetime(6), description TEXT, type enum ('EXCEPTION','PAYMENT','REFUND','SCHOLARSHIP','USAGE') not null, primary key (id)) engine=InnoDB;
create table user_achievements (achievement_level_id integer not null, is_displayed bit not null, id bigint not null auto_increment, unlocked_at datetime(6) not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table user_gamification_stats (total_competence integer, total_diligence integer, total_experience integer, updated_at datetime(6) not null, user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table user_images (id bigint not null auto_increment, nguoi_dung_id bigint not null, thoi_gian_tao datetime(6), mo_ta varchar(255), url_anh varchar(255), primary key (id)) engine=InnoDB;
create table user_point_logs (behavior_id integer, points_competence_earned integer, points_diligence_earned integer, points_experience_earned integer, created_at datetime(6) not null, id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=InnoDB;
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users (deleted bit not null, job_interest_enabled bit not null, id bigint not null auto_increment, ngay_tao datetime(6), password_changed_at datetime(6), refresh_token_expiry datetime(6), refresh_token varchar(500), anh_bia varchar(255), anh_dai_dien varchar(255), email varchar(255) not null, firstname varchar(255), keycloak_id varchar(255), lastname varchar(255), password varchar(255) not null, so_dien_thoai varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists coupons add constraint UKeplt0kkm9yf2of2lnx6c1oy9b unique (code);
alter table if exists form_templates add constraint UKf58cdd0lknth5f9iwnjqdxlxs unique (code);
alter table if exists gamification_behaviors add constraint UK75ousat2cj5frqvkqca28hr1y unique (name);
alter table if exists grades add constraint UKsgtmrgd3b4lgvaukkreggb95c unique (student_id, class_module_id);
alter table if exists notification_templates add constraint UKl0y8ajrytw3f9bj1kxa6r6w9e unique (name);
alter table if exists student_tuitions add constraint UKg7116h2p152ipvcca38ga46gi unique (student_id, tuition_route_id);
alter table if exists tuition_receipts add constraint UK79o38xobqja6k2fn1w1ls96y7 unique (payment_schedule_id);
alter table if exists tuition_receipts add constraint UK7vd1wkyg4ifvyyhrjosrm2cdx unique (transaction_id);
alter table if exists tuition_receipts add constraint UKminidbcu3h682bmmi4f94h4dy unique (receipt_code);
alter table if exists users add constraint UK366dgrd625s5659shyen79mmw unique (keycloak_id);
alter table if exists behavior_point_types add constraint FKahrqc0o8v406upoo84agi41nf foreign key (behavior_id) references gamification_behaviors (id);
alter table if exists behavior_point_types add constraint FKd0xnt15krc3r4hf98vx87goil foreign key (notification_template_id) references notification_templates (id);
alter table if exists behavior_point_types add constraint FKtfxeovnw66wf2aqfhxhlci6o8 foreign key (point_type_id) references gamification_point_types (id);
alter table if exists class_members add constraint FKhpn79nj3vw2wg5h0ggwiih027 foreign key (lop_id) references classes (id);
alter table if exists class_members add constraint FK1cuvia77hl9u4whorse3prmjo foreign key (nguoi_dung_id) references users (id);
alter table if exists class_module add constraint FKcfqtcvj3g6bsed7memqnupc5f foreign key (class_id) references classes (id);
alter table if exists class_module add constraint FKb9lo4if0ltspqdxwto2q6c3yq foreign key (module_id) references modules (id);
alter table if exists class_module_schedule_teacher add constraint FKr3sr1fjg1r5oj5jnkjthpltgk foreign key (class_module_schedule_id) references class_module_schedules (id);
alter table if exists class_module_schedule_teacher add constraint FKqo6vw3a3qu4n3j24gilwkbai1 foreign key (user_id) references users (id);
alter table if exists class_module_schedules add constraint FKth2dtohhkxwo1xcwmufq9e965 foreign key (class_id) references classes (id);
alter table if exists class_module_schedules add constraint FKle9a499s8ck0l4vitqh0jfusi foreign key (class_module_id) references class_module (id);
alter table if exists class_module_schedules add constraint FK878j8s2vjcrj3f0w1rinmgupf foreign key (instructor_id) references users (id);
alter table if exists class_module_schedules add constraint FK1sny079m2etfl9un81tcj97d1 foreign key (module_id) references modules (id);
alter table if exists class_module_schedules add constraint FKjj6hxjempddlapqlqvyi5885t foreign key (module_session_id) references module_sessions (id);
alter table if exists class_module_teacher add constraint FK9fstv5tvnv2c7s2vl6wib7sw7 foreign key (class_module_id) references class_module (id);
alter table if exists class_module_teacher add constraint FKmwo0xvuw20rxm2370i25fbc0m foreign key (user_id) references users (id);
alter table if exists classes add constraint FKthmk4awc7ft3lg8ud2behicfs foreign key (program_id) references programs (id);
alter table if exists comments add constraint FK9qgjxe34n8vrnyh2kmakujx3f foreign key (bai_viet_id) references posts (id);
alter table if exists comments add constraint FK51gt7c1y42b27n9djasdeaad0 foreign key (nguoi_dung_id) references users (id);
alter table if exists company_markets add constraint FKkcwv4hfufcoovgyl0lvm7vq9 foreign key (company_id) references companies (id);
alter table if exists company_products add constraint FK2tikxm14exdh2x0lyc96u8jux foreign key (company_id) references companies (id);
alter table if exists company_regions add constraint FK7i595yx80216e7r8bd1vl19gv foreign key (company_id) references companies (id);
alter table if exists company_technologies add constraint FK3jltkcvh9kehcbqp4c4aq2mvy foreign key (company_id) references companies (id);
alter table if exists contact_persons add constraint FKr7nuii3n8bji9ib8ghxqmltbs foreign key (company_id) references companies (id);
alter table if exists files add constraint FK3cfjbplxrqcb1n7qi9dsgckom foreign key (comment_id) references comments (id);
alter table if exists files add constraint FKkb7cbgxj34ff0yfuf7cqhhh1y foreign key (post_id) references posts (id);
alter table if exists files add constraint FKki6sgbw482hx0qfmfx8gjqblj foreign key (reply_comment_id) references reply_comments (id);
alter table if exists gamification_achievement_levels add constraint FKr6npnwc2rtddronrnnql5pqnl foreign key (achievement_id) references gamification_achievements (id);
alter table if exists gamification_achievement_levels add constraint FKgnnhx48i9qpi0caxd79rjc2wh foreign key (notification_template_id) references notification_templates (id);
alter table if exists gamification_behaviors add constraint FKdoxgok4bmxxo4a13fx6u2tsu9 foreign key (group_id) references gamification_behavior_groups (id);
alter table if exists gamification_behaviors add constraint FKfgbuhj1xm99r92xolros2ai7x foreign key (notification_template_competence_id) references notification_templates (id);
alter table if exists gamification_behaviors add constraint FKx0kgfuqefhkmpjnn6dtd7j77 foreign key (notification_template_diligence_id) references notification_templates (id);
alter table if exists gamification_behaviors add constraint FK8v0xcy7g0b2uwx8dh6uf13u3e foreign key (notification_template_experience_id) references notification_templates (id);
alter table if exists grade_history add constraint FKn3447sw7k0qt0j0uyavadnet5 foreign key (changed_by_user_id) references users (id);
alter table if exists grade_history add constraint FK45ak73yeaf9nls14n95lxt152 foreign key (grade_id) references grades (id);
alter table if exists grades add constraint FKnvql97ygjk2dxwipo235ysmw5 foreign key (class_module_id) references class_module (id);
alter table if exists grades add constraint FK66fb2j1vqc4xuq4svd7j3km3w foreign key (entered_by_user_id) references users (id);
alter table if exists grades add constraint FK2udi8qqpoqmopyp47iy76jeq6 foreign key (student_id) references users (id);
alter table if exists job_activities add constraint FKthtkxharljip442qmnmupnh1v foreign key (job_lead_id) references job_leads (id);
alter table if exists job_applications add constraint FKw5caporr7h1h1x6kh5dn764m foreign key (class_id) references classes (id);
alter table if exists job_applications add constraint FK9na8akp78w38mkoolybi83fui foreign key (company_id) references companies (id);
alter table if exists job_applications add constraint FKqxtt5v9mi302vt7gvti7wqfky foreign key (student_id) references users (id);
alter table if exists job_leads add constraint FK373skddkcq2xi346svvu97udx foreign key (student_id) references users (id);
alter table if exists module_sessions add constraint FKoh796q6qlryhvgexgu8924oi6 foreign key (module_id) references modules (id);
alter table if exists notifications add constraint FK9kxl0whvhifo6gw4tjq36v53k foreign key (receiver_id) references users (id);
alter table if exists notifications add constraint FK13vcnq3ukas06ho1yrbc5lrb5 foreign key (sender_id) references users (id);
alter table if exists password_reset_requests add constraint FK1xtvwnh0xfmemjmmgamr3y83f foreign key (user_id) references users (id);
alter table if exists posts add constraint FKnosuy4j2jyj4x29pd4ee36cdh foreign key (nguoi_dung_id) references users (id);
alter table if exists program_modules add constraint FK211y54rdollbrrxtbr3jl7yck foreign key (module_id) references modules (id);
alter table if exists program_modules add constraint FK5tva44ywu8ycp5k9u50cdjfko foreign key (program_id) references programs (id);
alter table if exists ranking add constraint FKdm0ihxbw4idqvhi6e97p23m4b foreign key (classes_id) references classes (id);
alter table if exists ranking add constraint FKbnq5thfli40vp5mghiwrfbccx foreign key (nguoi_dung_id) references users (id);
alter table if exists ranking_monthly add constraint FKdm2c59rpx7ebqa1xcx4hd0fw6 foreign key (class_id) references classes (id);
alter table if exists ranking_monthly add constraint FK253f6rg6k4hk5dfpqm9ka3c2e foreign key (user_id) references users (id);
alter table if exists reactions add constraint FK49rifnmyo1sd243acaysemlbw foreign key (comment_id) references comments (id);
alter table if exists reactions add constraint FKjpcjvbhkp9kcwqwaxa2do15aw foreign key (bai_viet_id) references posts (id);
alter table if exists reactions add constraint FK4twk7tpc7qcki5i92xg0fowaq foreign key (reply_comment_id) references reply_comments (id);
alter table if exists reactions add constraint FK75xmry0o93yw96pryvw8okbme foreign key (nguoi_dung_id) references users (id);
alter table if exists reply_comments add constraint FKwep51yn6mn16j5n0wyog1s5d foreign key (comments_id) references comments (id);
alter table if exists reply_comments add constraint FKquk23cbhxq4hg2w7yrkyawh2i foreign key (nguoi_dung_id) references users (id);
alter table if exists role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references permissions (id);
alter table if exists role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles (id);
alter table if exists student_forms add constraint FK3vekjis3fl6sitnd4r3ee0p4k foreign key (academic_user_id) references users (id);
alter table if exists student_forms add constraint FKr9d7lcrntkgf1t9iqfyiyehk8 foreign key (accountant_user_id) references users (id);
alter table if exists student_forms add constraint FKlncpgm6lx860tim0qtx1xj4bv foreign key (admin_user_id) references users (id);
alter table if exists student_forms add constraint FK9fl3uoimfxiuk7yl927elvmdl foreign key (class_id) references classes (id);
alter table if exists student_forms add constraint FK959s3oqvftvj9awqh82esph6o foreign key (coach_user_id) references users (id);
alter table if exists student_forms add constraint FKlosc2vn9hu755y8jmgt1505p foreign key (created_by_user_id) references users (id);
alter table if exists student_forms add constraint FKd0704s8jjw7g33vvhic1tka7j foreign key (student_id) references users (id);
alter table if exists student_forms add constraint FKgy9we4xlfbwbonxbjgb2qxdos foreign key (template_id) references form_templates (id);
alter table if exists student_payment_schedule_history add constraint FKjrvkn6k20rxbo9kq5muo1jsob foreign key (modified_by_user_id) references users (id);
alter table if exists student_payment_schedule_history add constraint FK6w122fm518bpdptcpw2nc6yaf foreign key (schedule_id) references student_payment_schedules (id);
alter table if exists student_payment_schedules add constraint FKooiktgp28liq8xmb9rowj0fo7 foreign key (student_tuition_id) references student_tuitions (id);
alter table if exists student_tuitions add constraint FK6gs8hck3dqtsllf7oayxlpry2 foreign key (student_id) references users (id);
alter table if exists student_tuitions add constraint FKhdn1adfkujhmhfklp7esed6pa foreign key (tuition_route_id) references tuition_routes (id);
alter table if exists tuition_installment_configs add constraint FKg6g0sboajvg5v0hle2q7u57nu foreign key (tuition_route_id) references tuition_routes (id);
alter table if exists tuition_receipts add constraint FKpnbkhgd170iqiy4etigx58g48 foreign key (collector_id) references users (id);
alter table if exists tuition_receipts add constraint FK4me63o5xro0nv603u7mtrq6ll foreign key (payment_schedule_id) references student_payment_schedules (id);
alter table if exists tuition_receipts add constraint FK2c4n5xsq7o9somb5psv3yef6 foreign key (transaction_id) references tuition_transactions (id);
alter table if exists tuition_routes add constraint FKi487hqit5swe2cq6ve94ga9r6 foreign key (program_id) references programs (id);
alter table if exists tuition_transactions add constraint FKb9h5g7on59ffnewdjerb0yg53 foreign key (performed_by) references users (id);
alter table if exists tuition_transactions add constraint FKhdj7ifbou6ssbankq9yh809v4 foreign key (student_tuition_id) references student_tuitions (id);
alter table if exists user_achievements add constraint FKpf5ihx08ubh1lm5gbnxdw6w4r foreign key (achievement_level_id) references gamification_achievement_levels (id);
alter table if exists user_images add constraint FKbycokffn4rq133hh2378el181 foreign key (nguoi_dung_id) references users (id);
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);

SET FOREIGN_KEY_CHECKS=1;

