ALTER TABLE permissions ADD COLUMN code VARCHAR(255);
UPDATE permissions SET code = name;
ALTER TABLE permissions MODIFY COLUMN code VARCHAR(255) NOT NULL UNIQUE;

ALTER TABLE roles ADD COLUMN code VARCHAR(255);
UPDATE roles SET code = name;
ALTER TABLE roles MODIFY COLUMN code VARCHAR(255) NOT NULL UNIQUE;
